# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.5
      uses: actions/setup-node@v3
      with:
        node-version: 16.5
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    # - run: npm test # skip because some weird npm dependency, maybe problem with version
    - run: cp *.md dist/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: Static Bundle
        path: dist/
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
           dist/*
